export const ROOTX = 'http://result.loonglog.com/';
export const TEST = ROOTX + 'index.php';

export const ROOT = 'http://115.159.56.141/index.php/';
export const SIGN_UP = ROOT + 'Home/Sign/sign';
export const SIGN_ON = ROOT + 'Home/Login/login';
export const VERIFY = ROOT + 'Home/Login/showVerify';
export const SIGN_OUT = ROOT + 'Home/Login/logout';
export const SIGN_ON_VERIFY = ROOT + 'Home/Login/verification';
export const LINK_LIST = ROOT + 'Home/Posts/getPostsList';  //帖子列表
export const PUBLISH_POSTS = ROOT + 'Home/Posts/publishPosts'; //发布帖子
export const ACCOUNT_INFO = ROOT + 'Home/User/getOneUser';  //用户信息
export const ACCOUNT_EDIT = ROOT + 'Home/User/editUserData';    //用户信息修改
export const PASSWORD_EDIT = ROOT + 'Home/User/editPasswd';  //密码修改
export const USER_POSTS = ROOT + 'Home/User/getUserPosts';  //获取用户已发布的帖子
export const PARENT_CLASSIFICATION_LIST = ROOT + 'Home/Classification/getParentClassificationList';    //获取所有主板块的信息
export const POST_CONTENT = ROOT + "Home/Posts/getOnePosts";  //帖子详情
export const REPLY_LIST = ROOT + "Home/Reply/getAllReply";  //获取某个帖子下的所有评论
export const ADD_REPLY = ROOT + "Home/Reply/addReply";  //发表评论
export const CLASS_INFO = ROOT + "Home/Classification/getOneClassification";    //获取某个分类的的信息
export const CLASS_POSTS = ROOT + "Home/Posts/getClassificationPosts";  //获取某个分类下的帖子列表
export const CLASS_TREE = ROOT + "Home/Classification/getTreeClassification";   //获取某个分类的树形结构，即子版块
export const SEARCH = ROOT + "Home/Posts/searchPostsByKeywords";    //搜索帖子
export const TOP_POSTS = ROOT + "Home/Posts/getTopPostsList";   //置顶帖子
export const RECOMMEND_POSTS = ROOT + "Home/Posts/getRecommendPostsList"; //推荐帖子